default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: philipbroadway  
  password: 
  host: localhost

development:
  <<: *default
  database: temp_check_development

test:
  <<: *default
  database: temp_check_test

production:
  <<: *default
  database: <%= ENV['TEMP_CHECK_DATABASE'] %>
  username: <%= ENV['TEMP_CHECK_DATABASE_USER'] %>
  password: <%= ENV['TEMP_CHECK_DATABASE_PASSWORD'] %>
